remote_theme: just-the-docs/just-the-docs
title: WaveVortexModel
description: Decompose and model rotating stratified flow with wave-vortex modes
search_enabled: true
compress_html:
  blanklines: true
