file(GLOB runtime_sources "${WV_REPOSITORY_ROOT}/PortableRuntime/src/*.cpp")
foreach(source IN LISTS runtime_sources)
  if(source MATCHES "WVOutputOrchestration.cpp$|WVOutputSchedule.cpp$")
    continue()
  endif()
  file(READ "${source}" contents)
  if(contents MATCHES "\\.eventCount\\(|\\.event\\(")
    message(FATAL_ERROR "Production source enumerates output-plan events: ${source}")
  endif()
  if(contents MATCHES "WVStateTriggeredOutputSchedule|WVTestQuadraticOutputSchedule")
    message(FATAL_ERROR "Production source dispatches on a schedule provider identity: ${source}")
  endif()
endforeach()
