classdef TestFreeSurfacePressureReference < matlab.unittest.TestCase
    methods (TestClassSetup)
        function addStudyPath(testCase)
            root = fileparts(fileparts(mfilename('fullpath')));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture(fullfile(root,'tools','nonlinear-study')));
        end
    end
    methods (Test, TestTags="full")
        function flatOperatorRecoversResolvedLinearPressure(testCase)
            wvt = WVTransformFreeSurfaceBoussinesq.fromStratification([1e5 1e5 1000],[6 6 33],N2Function=@(z)1e-4+0*z,apvModeCount=3,mdaModeCount=2,waveModeCount=4,inertialModeCount=3,nEVP=128);
            column = find(wvt.kNonzero>0 & wvt.lNonzero==0,1);
            wvt.Aw_p(1,column) = 0.002+0.003i;
            wvt.Aw_m(2,column) = 0.001-0.002i;
            wvt.Ag_q(1,column) = 1e-8;
            wvt.Ag_0(:,column) = [1e-8;-2e-8];
            wvt.Amda(1) = 0.001;
            wvt.Aio(1) = 0.002i;
            fields = wvt.reconstructFields(["u","v","w","eta","p","ssh"]);
            force = struct(u=wvt.f*fields.v,v=-wvt.f*fields.u,w=-reshape(wvt.N2,1,1,[]).*fields.eta);
            derivative.x = @(field) fourierDerivative(field,wvt.Lx,1);
            derivative.y = @(field) fourierDerivative(field,wvt.Ly,2);
            derivative.xi = @(field) wvt.diffZ(field);
            % Linearization freezes geometry at zero but retains the linear
            % dynamic surface-pressure data from the resolved mixed state.
            [pressure,diagnostics] = solveFreeSurfacePressureReference(zeros(size(fields.ssh)),force,wvt.g*fields.ssh,wvt.z,wvt.Lz,derivative);
            expected = fields.p/wvt.rho0;
            testCase.verifyLessThan(norm(pressure(:)-expected(:))/norm(expected(:)),2e-7)
            state = wvt.coefficientState();
            omega = wvt.waveFrequency(:,wvt.klNonzeroKhUniqueIndex);
            state.Aw_p = 1i*omega.*state.Aw_p;
            state.Aw_m = -1i*omega.*state.Aw_m;
            state.Aio = 1i*wvt.f*state.Aio;
            state.Ag_q(:) = 0;
            state.Ag_0(:) = 0;
            state.Amda(:) = 0;
            spectral = wvt.reconstructSpectralState(state=state);
            for name = ["u","v","w"]
                expected = wvt.transformToSpatialDomainWithFourier(spectral.(name));
                actual = diagnostics.acceleration.(name);
                scale = norm(force.(name)(:))+norm(expected(:));
                testCase.verifyLessThan(norm(actual(:)-expected(:))/scale,2e-6)
            end
        end

        function recoverManufacturedNonflatPressure(testCase)
            [x,y,xi,Lz,derivative] = referenceGrid(6,9);
            [X,Y,S] = ndgrid(x,y,1+xi/Lz);
            k = 2*pi/800;
            l = 2*pi/600;
            ssh = 12*cos(k*X(:,:,1))+8*sin(l*Y(:,:,1));
            gamma = 1+ssh/Lz;
            bx = S.*(-12*k*sin(k*X))./gamma;
            by = S.*(8*l*cos(l*Y))./gamma;
            expected = 0.2*cos(k*X).*sin(l*Y).*(1+S.^3)+0.4*S;
            px = -0.2*k*sin(k*X).*sin(l*Y).*(1+S.^3);
            py = 0.2*l*cos(k*X).*cos(l*Y).*(1+S.^3);
            pxi = (0.6*cos(k*X).*sin(l*Y).*S.^2+0.4)/Lz;
            % Analytic M grad(pi), plus a divergence-free acceleration with
            % zero bottom trace. Neither pressure nor force is generated by
            % the oracle's discrete matrix.
            solenoidal.u = 0.003*cos(k*X).*S;
            solenoidal.v = zeros(size(X));
            solenoidal.w = 0.003*k*Lz*sin(k*X).*S.^2/2;
            force.u = gamma.*(px-bx.*pxi)+solenoidal.u;
            force.v = gamma.*(py-by.*pxi)+solenoidal.v;
            force.w = -gamma.*(bx.*px+by.*py)+(1./gamma+gamma.*(bx.^2+by.^2)).*pxi+solenoidal.w;
            [actual,diagnostics] = solveFreeSurfacePressureReference(ssh,force,expected(:,:,end),xi,Lz,derivative);
            testCase.verifyEqual(actual,expected,AbsTol=2e-11)
            for name = ["u","v","w"]
                testCase.verifyEqual(diagnostics.acceleration.(name),solenoidal.(name),AbsTol=2e-12)
            end
            testCase.verifyLessThan(diagnostics.interiorDivergence,2e-13)
            testCase.verifyLessThan(diagnostics.endpointDivergence,2e-13)
        end

        function pressureClosesMappedInstantaneousAcceleration(testCase)
            [x,y,xi,Lz,derivative] = referenceGrid(6,13);
            [X,Y,S] = ndgrid(x,y,1+xi/Lz);
            k = 2*pi/800;
            l = 2*pi/600;
            hatted.u = 0.03*cos(k*X).*cos(l*Y).*S;
            hatted.v = 0.01*sin(k*X).*sin(l*Y).*S;
            hatted.w = Lz*(0.03*k-0.01*l)*sin(k*X).*cos(l*Y).*S.^2/2;
            hatted.ssh = 0.2*cos(k*X(:,:,1));
            hatted.eta = 0.2*cos(k*X).*S;
            zero = zeros(size(X));
            % Buoyancy is a prescribed smooth control here; this test does
            % not assert a finite-amplitude density/APE approximation.
            buoyancy = -1e-4*hatted.eta;
            rho0 = 1025;
            force = WVInternal.freeSurfaceMappedTendency(hatted,zero,buoyancy,xi,Lz,1e-4,rho0,derivative);
            [pressure,diagnostics] = solveFreeSurfacePressureReference(hatted.ssh,force,9.81*hatted.ssh,xi,Lz,derivative);
            actual = WVInternal.freeSurfaceMappedTendency(hatted,rho0*pressure,buoyancy,xi,Lz,1e-4,rho0,derivative);
            for name = ["u","v","w"]
                testCase.verifyEqual(actual.(name),diagnostics.acceleration.(name),AbsTol=2e-14)
            end
            divergence = derivative.x(actual.u)+derivative.y(actual.v)+derivative.xi(actual.w);
            testCase.verifyLessThan(max(abs(divergence(:,:,2:end-1)),[],'all'),2e-13)
            testCase.verifyLessThan(diagnostics.bottomAcceleration,2e-13)
            testCase.verifyLessThan(diagnostics.surfacePressureResidual,2e-13)
            testCase.verifyEqual(actual.ssh,hatted.w(:,:,end),AbsTol=0)
        end
    end
end

function [x,y,xi,Lz,derivative] = referenceGrid(n,nz)
Lz = 100;
x = (0:n-1).'*800/n;
y = (0:n-1).'*600/n;
xi = -Lz*(1+cos(pi*(0:nz-1).'/(nz-1)))/2;
weights = (-1).^(0:nz-1).';
weights([1 end]) = weights([1 end])/2;
distance = xi-xi.';
distance(1:nz+1:end) = 1;
matrix = (weights.'./weights)./distance;
matrix(1:nz+1:end) = 0;
matrix(1:nz+1:end) = -sum(matrix,2);
derivative.xi = @(field) reshape(reshape(field,[],nz)*matrix.',size(field));
derivative.x = @(field) fourierDerivative(field,800,1);
derivative.y = @(field) fourierDerivative(field,600,2);
end

function result = fourierDerivative(field,L,dimension)
n = size(field,dimension);
k = (2*pi/L)*[0:n/2-1 0 -n/2+1:-1];
shape = ones(1,ndims(field));
shape(dimension) = n;
result = real(ifft(1i*reshape(k,shape).*fft(field,[],dimension),[],dimension));
end
