function constants = wvCompiledBackendConstants(overrides)
classFile = string(which("WVCompiledBackend"));
if classFile == ""
    error("WaveVortexModel:CompiledBackendLocation","WVCompiledBackend must be on the MATLAB path.");
end
packageRoot = string(fileparts(fileparts(classFile)));
if isfield(overrides,"PackageRoot")
    packageRoot = string(overrides.PackageRoot);
end
cacheRoot = fullfile(packageRoot,".compiled-backend-cache");
moduleName = "wv_compiled_backend_mex";
constants = struct( ...
    "schemaVersion","1.0.0", ...
    "providerId","native-neon-pthreads", ...
    "providerVersion","3.3.11", ...
    "sourceURL","https://fftw.org/pub/fftw/fftw-3.3.11.tar.gz", ...
    "sourceURLs",["https://fftw.org/pub/fftw/fftw-3.3.11.tar.gz" "http://fftw.org/pub/fftw/fftw-3.3.11.tar.gz"], ...
    "sourceSHA256","5630c24cdeb33b131612f7eb4b1a9934234754f9f388ff8617458d0be6f239a1", ...
    "configureFlags","--host=aarch64-apple-darwin --enable-neon --enable-threads --disable-fortran --disable-openmp --enable-shared --disable-static", ...
    "compilerFlags","-O3 -mcpu=native", ...
    "deploymentTarget","13.3", ...
    "threadBackend","pthreads", ...
    "minimumRelease","R2025b", ...
    "contractVersion",4, ...
    "packageRoot",packageRoot, ...
    "cacheRoot",string(cacheRoot), ...
    "archivePath",string(fullfile(cacheRoot,"downloads","fftw-3.3.11.tar.gz")), ...
    "sourceDirectory",string(fullfile(cacheRoot,"source","fftw-3.3.11")), ...
    "buildDirectory",string(fullfile(cacheRoot,"build","native-neon-pthreads")), ...
    "installDirectory",string(fullfile(cacheRoot,"provider","native-neon-pthreads")), ...
    "stageDirectory",string(fullfile(cacheRoot,"stage")), ...
    "stateDirectory",string(fullfile(cacheRoot,"state")), ...
    "attemptPath",string(fullfile(cacheRoot,"state","build-attempt.json")), ...
    "recordPath",string(fullfile(cacheRoot,"state","validated-build.json")), ...
    "moduleName",moduleName, ...
    "installedModule",string(fullfile(packageRoot,moduleName+"."+mexext)), ...
    "adapterDirectory",string(fullfile(packageRoot,"CompiledKernel","adapters","native-fftw")), ...
    "coreSourceDirectory",string(fullfile(packageRoot,"CompiledKernel","src")), ...
    "coreIncludeDirectory",string(fullfile(packageRoot,"CompiledKernel","include")));
end
