function constants = wvCompiledBackendConstants(overrides)
classFile = string(which("WVCompiledBackend"));
if classFile == ""
    error("WaveVortexModel:CompiledBackendLocation","WVCompiledBackend must be on the MATLAB path.");
end
classRoot = string(fileparts(fileparts(classFile)));
packageRoot = classRoot;
if isfield(overrides,"PackageRoot")
    packageRoot = string(overrides.PackageRoot);
end
packageRoot = canonicalPath(packageRoot);
architecture = string(computer("arch"));
if isfield(overrides,"Architecture"), architecture = string(overrides.Architecture); end
release = string(version("-release"));
if isfield(overrides,"Release"), release = string(overrides.Release); end
release = "R"+regexprep(release,'^[Rr]+','');
packageKey = sha256Text(packageRoot+newline+architecture+newline+release);
% FFTW configure rejects whitespace in its source directory. MATLAB prefdir on
% macOS uses "Application Support", so compiled artifacts use the native cache.
userHome = string(java.lang.System.getProperty("user.home"));
cacheRoot = fullfile(userHome,"Library","Caches","WaveVortexModel","compiled-backend-v1",architecture,release,packageKey);
if isfield(overrides,"CacheRoot"), cacheRoot = string(overrides.CacheRoot); end
moduleName = "wv_compiled_backend_mex";
provider = readProviderManifest(fullfile(classRoot,"CompiledKernel","native-fftw-provider.env"));
constants = struct( ...
    "schemaVersion","1.0.0", ...
    "providerId",provider.WV_FFTW_PROVIDER_ID, ...
    "providerVersion",provider.WV_FFTW_VERSION, ...
    "sourceURL",provider.WV_FFTW_SOURCE_URL, ...
    "sourceURLs",[provider.WV_FFTW_SOURCE_URL replace(provider.WV_FFTW_SOURCE_URL,"https://","http://")], ...
    "sourceSHA256",provider.WV_FFTW_SOURCE_SHA256, ...
    "configureFlags",provider.WV_FFTW_CONFIGURE_FLAGS, ...
    "compilerFlags",provider.WV_FFTW_COMPILER_FLAGS, ...
    "deploymentTarget",provider.WV_FFTW_DEPLOYMENT_TARGET, ...
    "threadBackend","pthreads", ...
    "minimumRelease","R2025b", ...
    "contractVersion",4, ...
    "compactConstantDefault",true, ... % Qualified retained compact execution schedule.
    "horizontalOuterWorkers",12, ...
    "pointwiseWorkers",12, ... % Selected issue #358 worker policy.
    "executionPolicyIdentifier","constant-stage-workers-v1", ...
    "packageRoot",packageRoot, ...
    "packageKey",packageKey, ...
    "cacheLocationPolicy","user-cache-package-path-v1", ...
    "cacheRoot",string(cacheRoot), ...
    "archivePath",string(fullfile(cacheRoot,"downloads","fftw-3.3.11.tar.gz")), ...
    "sourceDirectory",string(fullfile(cacheRoot,"source","fftw-3.3.11")), ...
    "buildDirectory",string(fullfile(cacheRoot,"build","native-neon-pthreads")), ...
    "installDirectory",string(fullfile(cacheRoot,"provider","native-neon-pthreads")), ...
    "stageDirectory",string(fullfile(cacheRoot,"stage")), ...
    "stateDirectory",string(fullfile(cacheRoot,"state")), ...
    "attemptPath",string(fullfile(cacheRoot,"state","build-attempt.json")), ...
    "recordPath",string(fullfile(cacheRoot,"state","validated-build.json")), ...
    "moduleName",moduleName, ...
    "moduleDirectory",string(fullfile(cacheRoot,"module")), ...
    "installedModule",string(fullfile(cacheRoot,"module",moduleName+"."+mexext)), ...
    "adapterDirectory",string(fullfile(packageRoot,"CompiledKernel","adapters","native-fftw")), ...
    "coreSourceDirectory",string(fullfile(packageRoot,"CompiledKernel","src")), ...
    "coreIncludeDirectory",string(fullfile(packageRoot,"CompiledKernel","include")), ...
    "runtimeSourceDirectory",string(fullfile(packageRoot,"PortableRuntime","src")), ...
    "runtimeIncludeDirectory",string(fullfile(packageRoot,"PortableRuntime","include")));
end

function pathname = canonicalPath(pathname)
[status,output] = system("/bin/realpath "+shellQuote(pathname));
if status ~= 0
    error("WaveVortexModel:CompiledBackendPath","Unable to resolve %s.",pathname);
end
pathname = string(strtrim(output));
end

function hash = sha256Text(value)
bytes = unicode2native(char(value),"UTF-8");
digest = java.security.MessageDigest.getInstance("SHA-256");
digest.update(bytes);
hash = string(lower(reshape(dec2hex(typecast(digest.digest(),"uint8"),2).',1,[])));
end

function value = shellQuote(value)
value = "'"+replace(string(value),"'","'""'""'")+"'";
end

function values = readProviderManifest(path)
if ~isfile(path)
    error("WaveVortexModel:CompiledBackendProviderManifestMissing","Native FFTW provider manifest is missing: %s",path);
end
lines = strip(splitlines(string(fileread(path))));
lines(lines == "") = [];
values = struct;
for line = lines.'
    separator = strfind(line,"=");
    if isempty(separator)
        error("WaveVortexModel:CompiledBackendProviderManifestInvalid","Invalid native FFTW provider manifest line: %s",line);
    end
    name = extractBefore(line,separator(1));
    value = extractAfter(line,separator(1));
    if strlength(value) >= 2 && startsWith(value,'"') && endsWith(value,'"')
        value = extractBetween(value,2,strlength(value)-1);
    end
    values.(name) = value;
end
required = ["WV_FFTW_PROVIDER_ID" "WV_FFTW_VERSION" "WV_FFTW_SOURCE_URL" "WV_FFTW_SOURCE_SHA256" "WV_FFTW_CONFIGURE_FLAGS" "WV_FFTW_COMPILER_FLAGS" "WV_FFTW_DEPLOYMENT_TARGET"];
if any(~isfield(values,required))
    error("WaveVortexModel:CompiledBackendProviderManifestInvalid","Native FFTW provider manifest is incomplete.");
end
end
