function result = generatePortableVariableCatalog(options)
% Generate the portable variable catalog from MATLAB annotations.
%
% `WVVariableAnnotation` is the authoritative source for scientific names,
% dimensions, units, descriptions, complexity, cache behavior, and NetCDF
% attributes. The portability supplement records only C++ implementation
% facts that those annotations do not represent.
%
% - Topic: Developer tools
% - Declaration: result = generatePortableVariableCatalog()
% - Parameter repositoryRoot: (optional) WaveVortexModel authoring root
% - Returns result: generated paths and the normalized catalog record
arguments
    options.repositoryRoot (1,1) string = defaultRepositoryRoot()
end

repositoryRoot = canonicalPath(options.repositoryRoot);
supplementPath = fullfile(repositoryRoot,"PortableRuntime","contracts", ...
    "portable-variable-supplement-v1.json");
catalogPath = fullfile(repositoryRoot,"PortableRuntime","contracts", ...
    "portable-variable-catalog-v1.json");
headerPath = fullfile(repositoryRoot,"PortableRuntime","include", ...
    "WaveVortexRuntime","generated","WVPortableVariableCatalog.hpp");

supplement = jsondecode(fileread(supplementPath));
mustBeValidSupplement(supplement);
annotations = authoritativeAnnotations(supplement.variables);

variables = repmat(emptyVariableRecord(),numel(supplement.variables),1);
for iVariable = 1:numel(supplement.variables)
    definition = supplement.variables(iVariable);
    annotation = annotations(char(definition.name));
    variables(iVariable) = normalizedRecord(definition,annotation, ...
        supplement.primitiveDependencies);
end

catalog = struct( ...
    schema="portable-variable-catalog-v1", ...
    semanticContract="wave-vortex-portable-pair-v1", ...
    authoritativeType="WVVariableAnnotation", ...
    portabilitySupplement="PortableRuntime/contracts/portable-variable-supplement-v1.json", ...
    variables=variables);

writeText(catalogPath,string(jsonencode(catalog,PrettyPrint=true)) + newline);
writeText(headerPath,renderHeader(variables));
result = struct(catalogPath=catalogPath,headerPath=headerPath,catalog=catalog);
end

function root = defaultRepositoryRoot()
root = string(fileparts(fileparts(mfilename("fullpath"))));
end

function path = canonicalPath(path)
path = string(path);
if ~isfolder(path)
    error("WaveVortexModel:InvalidRepositoryRoot", ...
        "Repository root does not exist: %s",path);
end
originalDirectory = string(pwd);
cleanup = onCleanup(@() cd(originalDirectory));
cd(path);
path = string(pwd);
clear cleanup
end

function mustBeValidSupplement(supplement)
if ~isfield(supplement,"schema") || supplement.schema ~= "portable-variable-supplement-v1"
    error("WaveVortexModel:InvalidPortableVariableSupplement", ...
        "The portability supplement has an unsupported schema.");
end
variables = supplement.variables;
ordinals = double([variables.ordinal]);
names = string({variables.name});
if ~isequal(ordinals,0:numel(variables)-1) || numel(unique(names)) ~= numel(names)
    error("WaveVortexModel:InvalidPortableVariableSupplement", ...
        "Portable variable ordinals must be contiguous and names unique.");
end
end

function annotations = authoritativeAnnotations(definitions)
annotations = containers.Map(KeyType="char",ValueType="any");
coefficientNames = {'Ap','Am','A0'};
allPropertyAnnotations = WVTransform.propertyAnnotationsForTransform( ...
    coefficientNames{:},spectralDimensionNames={'j','kl'});
for iAnnotation = 1:numel(allPropertyAnnotations)
    annotation = allPropertyAnnotations(iAnnotation);
    if ismember(annotation.name,coefficientNames)
        annotations(annotation.name) = annotation;
    end
end

allNames = string({definitions.name});
fieldNames = cellstr(allNames(4:end));
operations = WVTransform.classDefinedOperationForKnownVariable( ...
    fieldNames{:},spatialDimensionNames={'x','y','z'}, ...
    spectralDimensionNames={'j','kl'});
for iOperation = 1:numel(operations)
    annotation = operations(iOperation).outputVariables;
    annotations(annotation.name) = annotation;
end
if annotations.Count ~= numel(definitions)
    error("WaveVortexModel:IncompletePortableVariableCatalog", ...
        "Expected %d authoritative annotations, found %d.", ...
        numel(definitions),annotations.Count);
end
end

function record = emptyVariableRecord()
record = struct( ...
    ordinal=0, ...
    name="", ...
    cppIdentifier="", ...
    dimensions=strings(1,0), ...
    units="", ...
    description="", ...
    isComplex=false, ...
    isVariableWithLinearTimeStep=false, ...
    isVariableWithNonlinearTimeStep=false, ...
    isDependentOnApAmA0=false, ...
    portableKind="", ...
    naturalRank="", ...
    samplingModes=strings(1,0), ...
    primitiveDependencyMask=uint64(0), ...
    movingPrimitiveChannel=int8(-1), ...
    netCDFAttributes=repmat(struct(name="",value=""),0,1));
end

function record = normalizedRecord(definition,annotation,dependencyValues)
record = emptyVariableRecord();
record.ordinal = double(definition.ordinal);
record.name = string(annotation.name);
record.cppIdentifier = string(definition.cppIdentifier);
record.dimensions = string(annotation.dimensions);
record.units = string(annotation.units);
record.description = string(annotation.description);
record.isComplex = logical(annotation.isComplex);
record.isVariableWithLinearTimeStep = logical(annotation.isVariableWithLinearTimeStep);
record.isVariableWithNonlinearTimeStep = logical(annotation.isVariableWithNonlinearTimeStep);
record.isDependentOnApAmA0 = logical(annotation.isDependentOnApAmA0);
record.portableKind = string(definition.portableKind);
record.naturalRank = string(definition.naturalRank);
record.samplingModes = string(definition.samplingModes(:)).';
record.movingPrimitiveChannel = int8(definition.movingPrimitiveChannel);

dependencyNames = string(definition.primitiveDependencies);
for iDependency = 1:numel(dependencyNames)
    name = char(dependencyNames(iDependency));
    if ~isfield(dependencyValues,name)
        error("WaveVortexModel:InvalidPortableVariableSupplement", ...
            "Unknown primitive dependency %s.",name);
    end
    record.primitiveDependencyMask = bitor(record.primitiveDependencyMask, ...
        uint64(dependencyValues.(name)));
end

attributes = annotation.attributes;
attributeNames = string(keys(attributes));
supplementAttributes = definition.netCDFAttributes;
if isstruct(supplementAttributes)
    attributeNames = [attributeNames,string(fieldnames(supplementAttributes)).']; %#ok<AGROW>
end
attributeNames = sort(unique(attributeNames));
record.netCDFAttributes = repmat(struct(name="",value=""),numel(attributeNames),1);
for iAttribute = 1:numel(attributeNames)
    name = attributeNames(iAttribute);
    if isKey(attributes,char(name))
        value = string(attributes(char(name)));
    else
        value = string(supplementAttributes.(char(name)));
    end
    record.netCDFAttributes(iAttribute) = struct(name=name,value=value);
end
end

function text = renderHeader(variables)
lines = [ ...
    "// Generated by tools/generatePortableVariableCatalog.m. Do not edit."; ...
    "#pragma once"; ...
    ""; ...
    "#include <array>"; ...
    "#include <cstddef>"; ...
    "#include <cstdint>"; ...
    "#include <string_view>"; ...
    ""; ...
    "namespace wavevortex::runtime {"; ...
    ""; ...
    "enum class WVPortableVariable : std::uint8_t {" ...
    ];
for iVariable = 1:numel(variables)
    definition = variables(iVariable);
    lines(end+1) = "  " + definition.cppIdentifier + " = " + ...
        definition.ordinal + ","; %#ok<AGROW>
end
lines = [lines; ...
    "  count = " + numel(variables) + ","; ...
    "  invalid = 255"; ...
    "};"; ...
    ""; ...
    "enum class WVPortableVariableKind : std::uint8_t { coefficient, field };"; ...
    "enum class WVPortableNaturalRank : std::uint8_t { coefficient, scalar, vertical, horizontal, volume };"; ...
    ""; ...
    "enum WVPortableSamplingMode : std::uint8_t {"; ...
    "  portableCoefficientSampling = 1U << 0,"; ...
    "  portableFullGridSampling = 1U << 1,"; ...
    "  portableFixedVerticalProfileSampling = 1U << 2,"; ...
    "  portablePositionSampling = 1U << 3"; ...
    "};"; ...
    ""; ...
    "struct WVPortableNetCDFAttribute {"; ...
    "  const char *name;"; ...
    "  const char *value;"; ...
    "};"; ...
    ""; ...
    "struct WVPortableVariableMetadata {"; ...
    "  WVPortableVariable identifier;"; ...
    "  std::uint8_t ordinal;"; ...
    "  const char *name;"; ...
    "  std::array<const char *, 3> dimensions;"; ...
    "  std::uint8_t dimensionCount;"; ...
    "  const char *units;"; ...
    "  const char *description;"; ...
    "  bool isComplex;"; ...
    "  bool isVariableWithLinearTimeStep;"; ...
    "  bool isVariableWithNonlinearTimeStep;"; ...
    "  bool isDependentOnApAmA0;"; ...
    "  WVPortableVariableKind kind;"; ...
    "  WVPortableNaturalRank naturalRank;"; ...
    "  std::uint8_t samplingMask;"; ...
    "  std::uint64_t primitiveDependencyMask;"; ...
    "  std::int8_t movingPrimitiveChannel;"; ...
    "  WVPortableNetCDFAttribute netCDFAttribute;"; ...
    "  std::uint8_t netCDFAttributeCount;"; ...
    "};"; ...
    ""; ...
    "inline constexpr std::array<WVPortableVariableMetadata, " + numel(variables) + ">"; ...
    "    WVPortableVariableCatalog{{" ...
    ];
for iVariable = 1:numel(variables)
    variable = variables(iVariable);
    dimensions = [variable.dimensions,strings(1,3-numel(variable.dimensions))];
    if isempty(variable.netCDFAttributes)
        attributeName = "";
        attributeValue = "";
        attributeCount = 0;
    else
        if numel(variable.netCDFAttributes) > 1
            error("WaveVortexModel:UnsupportedPortableVariableAttributeCount", ...
                "The generated C++ v1 catalog supports one static NetCDF attribute per variable.");
        end
        attributeName = variable.netCDFAttributes(1).name;
        attributeValue = variable.netCDFAttributes(1).value;
        attributeCount = 1;
    end
    line = "        {WVPortableVariable::" + variable.cppIdentifier + ...
        ", " + variable.ordinal + ", " + cppString(variable.name) + ...
        ", {{" + join(arrayfun(@cppString,dimensions),", ") + "}}, " + ...
        numel(variable.dimensions) + ", " + cppString(variable.units) + ...
        ", " + cppString(variable.description) + ", " + ...
        cppBoolean(variable.isComplex) + ", " + ...
        cppBoolean(variable.isVariableWithLinearTimeStep) + ", " + ...
        cppBoolean(variable.isVariableWithNonlinearTimeStep) + ", " + ...
        cppBoolean(variable.isDependentOnApAmA0) + ...
        ", WVPortableVariableKind::" + variable.portableKind + ...
        ", WVPortableNaturalRank::" + variable.naturalRank + ", " + ...
        samplingMask(variable.samplingModes) + ", " + ...
        string(variable.primitiveDependencyMask) + ", " + ...
        string(variable.movingPrimitiveChannel) + ", {" + ...
        cppString(attributeName) + ", " + cppString(attributeValue) + ...
        "}, " + attributeCount + "}";
    if iVariable ~= numel(variables)
        line = line + ",";
    end
    lines(end+1) = line; %#ok<AGROW>
end
lines = [lines; ...
    "    }};"; ...
    ""; ...
    "inline constexpr const WVPortableVariableMetadata *"; ...
    "portableVariableMetadata(WVPortableVariable identifier) noexcept {"; ...
    "  const auto ordinal = static_cast<std::size_t>(identifier);"; ...
    "  return ordinal < WVPortableVariableCatalog.size()"; ...
    "             ? &WVPortableVariableCatalog[ordinal]"; ...
    "             : nullptr;"; ...
    "}"; ...
    ""; ...
    "inline constexpr const WVPortableVariableMetadata *"; ...
    "findPortableVariable(std::string_view name) noexcept {"; ...
    "  for (const auto &variable : WVPortableVariableCatalog)"; ...
    "    if (name == variable.name)"; ...
    "      return &variable;"; ...
    "  return nullptr;"; ...
    "}"; ...
    ""; ...
    "inline constexpr std::size_t portableVariableCatalogBytes() noexcept {"; ...
    "  return sizeof(WVPortableVariableCatalog);"; ...
    "}"; ...
    ""; ...
    "} // namespace wavevortex::runtime"; ...
    "" ...
    ];
text = join(lines,newline);
end

function mask = samplingMask(modes)
mask = uint8(0);
for mode = modes
    switch mode
        case "coefficients"
            mask = bitor(mask,uint8(1));
        case "fullGrid"
            mask = bitor(mask,uint8(2));
        case "fixedVerticalProfiles"
            mask = bitor(mask,uint8(4));
        case "positions"
            mask = bitor(mask,uint8(8));
        otherwise
            error("WaveVortexModel:InvalidPortableVariableSupplement", ...
                "Unknown sampling mode %s.",mode);
    end
end
mask = string(mask);
end

function value = cppBoolean(value)
if value
    value = "true";
else
    value = "false";
end
end

function value = cppString(value)
value = string(value);
value = replace(value,"\","\\");
value = replace(value,string(char(34)),string([char(92),char(34)]));
value = replace(value,newline,"\\n");
value = string(char(34)) + value + string(char(34));
end

function writeText(path,text)
folder = fileparts(path);
if ~isfolder(folder)
    mkdir(folder);
end
fileId = fopen(path,"w");
if fileId < 0
    error("WaveVortexModel:PortableVariableCatalogWriteFailed", ...
        "Unable to open %s for writing.",path);
end
cleanup = onCleanup(@() fclose(fileId));
fprintf(fileId,"%s",text);
end
