function result = generatePortableCompatibilityMatrix(options)
% Generate the standard assembly without changing its source-owned slices.
arguments
    options.repositoryRoot (1,1) string = string(fileparts(fileparts(mfilename("fullpath"))))
    options.outputRoot (1,1) string = ""
end
root=options.repositoryRoot;
output=options.outputRoot; if strlength(output)==0, output=root; end
matrix=portableCompatibilityDefinition(root);
validation=validatePortableCompatibilityMatrix(matrix,repositoryRoot=root,expected=matrix);
catalogPath=fullfile(output,"PortableRuntime","contracts","portable-compatibility-matrix-v1.json");
documentationPath=fullfile(output,"PortableRuntime","COMPATIBILITY.md");
writeText(catalogPath,string(jsonencode(serialized(matrix),PrettyPrint=true))+newline);
writeText(documentationPath,renderDocumentation(matrix));
result=struct(catalogPath=catalogPath,documentationPath=documentationPath,matrix=matrix,validation=validation);
end
function value=serialized(value)
% MATLAB otherwise encodes an empty string array as an empty numeric array and
% a singleton struct as an object; these fields are always JSON collections.
for field=["sources","versions","witnesses","rows","exclusions"]
    value.(field)=num2cell(value.(field));
end
for field=string(fieldnames(value.inventory))'
    value.inventory.(field)=cellstr(value.inventory.(field));
end
for k=1:numel(value.witnesses)
    value.witnesses{k}.coverage.rowIds=cellstr(value.witnesses{k}.coverage.rowIds);
end
for k=1:numel(value.rows), value.rows{k}.fixtures=cellstr(value.rows{k}.fixtures); end
for k=1:numel(value.exclusions), value.exclusions{k}.fixtures=cellstr(value.exclusions{k}.fixtures); end
end
function text=renderDocumentation(matrix)
lines=["# Standard portable compatibility";""; ...
    "Generated by `generatePortableCompatibilityMatrix`. Edit the source catalogs or fixture bindings, then regenerate.";""; ...
    "The assembly joins the MATLAB built-in inventory, portable contracts, and exact fixture scopes. A supported row means an applicable fixture is assigned; it does not assert a fresh execution on every provider or platform. Issue #307 owns the independent readiness decision.";""; ...
    "Current coverage is **"+matrix.completion+"**. Standard parity readiness remains **false**. Any remaining unqualified rows distinguish missing portable implementations from missing exact-pair fixture evidence; supported sampling rows retain their individual witness assignments.";""; ...
    "| Slice | Supported | Intentional incompatibility | Unqualified |";"| --- | ---: | ---: | ---: |"];
for slice=unique(string({matrix.rows.slice}),"stable")
    rows=matrix.rows(string({matrix.rows.slice})==slice); status=string({rows.status});
    lines(end+1)="| "+slice+" | "+sum(status=="supported")+" | "+sum(status=="intentional-incompatibility")+" | "+sum(status=="unqualified")+" |"; %#ok<AGROW>
end
lines=[lines;"";"## Tracked gaps";""; ...
    "The lifecycle slice uses six AA-on representative compositions spanning all continuation directions, rather than every cross-feature combination. Observer and field slices retain exact antialias settings. Position rows cover fixed, event, and moving sampling through independent interpolation witnesses, including the forty constant-adapter pairs completed in #454. Exact configuration, sampling, output-layout, restart-state, and fixture assignments are retained in [the JSON matrix](contracts/portable-compatibility-matrix-v1.json). These grouped counts do not relax its individual rows.";""; ...
    "| Reason | Exact rows | Issue |";"| --- | ---: | --- |"];
gaps=matrix.rows(string({matrix.rows.status})=="unqualified");
if isempty(gaps)
    lines(end+1)="| *(none)* | 0 | — |"; %#ok<AGROW>
else
    for reason=unique(string({gaps.reason}),"stable")
        selected=gaps(string({gaps.reason})==reason); count=numel(selected);
        issue=join("#"+unique([selected.issue]),", ");
        lines(end+1)="| "+reason+" | "+count+" | "+issue+" |"; %#ok<AGROW>
    end
end
lines=[lines;"";"## Contract versions";"";"| Identity | Version | Authority |";"| --- | --- | --- |"];
for item=reshape(matrix.versions,1,[])
    lines(end+1)="| `"+item.id+"` | "+string(item.version)+" | [source](../"+item.source+") |"; %#ok<AGROW>
end
lines=[lines;"";"Observation payload schema identifiers are instance-owned; the observation version above is the shared validation contract. The evenly spaced schedule entry applies to that built-in schedule, not arbitrary schedule payloads.";""; ...
    "## Explicit exclusions";"";"| Identity | Reason |";"| --- | --- |"];
for item=reshape(matrix.exclusions,1,[])
    lines(end+1)="| `"+item.id+"` | "+replace(item.reason,"|","\\|")+" |"; %#ok<AGROW>
end
lines=[lines;"";"## Verification";""; ...
    "`TestPortableCompatibilityMatrix` checks current MATLAB registration and transform discovery, source digests, version authorities, exact fixture scopes, and mutations that remove or contradict coverage. The cheap CI provenance gate also checks fixture declarations and complete-suite registration. Existing leaf qualification receipts remain separate and keep their original measured source identities.";""];
text=join(lines,newline);
end
function writeText(path,text)
folder=fileparts(path); if ~isfolder(folder), mkdir(folder); end
fid=fopen(path,'w'); if fid<0, error("WaveVortexModel:CompatibilityWriteFailed","Cannot write %s.",path); end
cleanup=onCleanup(@()fclose(fid)); fwrite(fid,char(text),'char');
end
