function result = generatePortableVariableCatalog(options)
% Generate the portable variable catalog from MATLAB annotations.
%
% `WVVariableAnnotation` is the authoritative source for scientific names,
% dimensions, units, descriptions, complexity, cache behavior, and NetCDF
% attributes. The portability supplement records only C++ implementation
% facts that those annotations do not represent.
%
% - Topic: Developer tools
% - Declaration: result = generatePortableVariableCatalog()
% - Parameter repositoryRoot: (optional) WaveVortexModel authoring root
% - Returns result: generated paths and the normalized catalog record
arguments
    options.repositoryRoot (1,1) string = defaultRepositoryRoot()
end

repositoryRoot = canonicalPath(options.repositoryRoot);
supplementPath = fullfile(repositoryRoot,"PortableRuntime","contracts", ...
    "portable-variable-supplement-v1.json");
catalogPath = fullfile(repositoryRoot,"PortableRuntime","contracts", ...
    "portable-variable-catalog-v1.json");
headerPath = fullfile(repositoryRoot,"PortableRuntime","include", ...
    "WaveVortexRuntime","generated","WVPortableVariableCatalog.hpp");

supplement = jsondecode(fileread(supplementPath));
mustBeValidSupplement(supplement);
annotations = authoritativeAnnotations(supplement.variables(1:23));

inventory = portableVariableAnnotations();
for iEntry = 1:numel(inventory)
    a = inventory(iEntry).annotation;
    if ~isKey(annotations,char(a.name)), annotations(char(a.name)) = a; end
end
if ~isequal(sort(string(keys(annotations))),sort(string({supplement.variables.name})))
    error("WaveVortexModel:IncompletePortableVariableCatalog","The registered inventory and append-only supplement disagree.");
end

variables = repmat(emptyVariableRecord(),numel(supplement.variables),1);
for iVariable = 1:numel(supplement.variables)
    definition = supplement.variables(iVariable);
    annotation = annotations(char(definition.name));
    variables(iVariable) = normalizedRecord(definition,annotation, ...
        supplement.primitiveDependencies);
end

catalog = struct( ...
    schema="portable-variable-catalog-v1", ...
    semanticContract="wave-vortex-portable-pair-v1", ...
    authoritativeType="WVVariableAnnotation", ...
    portabilitySupplement="PortableRuntime/contracts/portable-variable-supplement-v1.json", ...
    variables=variables);
catalog = addDiagnosticContracts(catalog,supplement,inventory);
validatePortableVariableCatalog(catalog);

writeText(catalogPath,string(jsonencode(catalog,PrettyPrint=true)) + newline);
writeText(headerPath,renderHeader(variables));
contractHeaderPath = fullfile(fileparts(headerPath),"WVPortableVariableContracts.hpp");
documentationPath = fullfile(repositoryRoot,"PortableRuntime","VARIABLES.md");
writeText(contractHeaderPath,renderPortableVariableContracts(catalog));
writeText(documentationPath,renderVariableDocumentation(catalog));
result = struct(catalogPath=catalogPath,headerPath=headerPath, ...
    contractHeaderPath=contractHeaderPath,documentationPath=documentationPath,catalog=catalog);
end

function root = defaultRepositoryRoot()
root = string(fileparts(fileparts(mfilename("fullpath"))));
end

function path = canonicalPath(path)
path = string(path);
if ~isfolder(path)
    error("WaveVortexModel:InvalidRepositoryRoot", ...
        "Repository root does not exist: %s",path);
end
originalDirectory = string(pwd);
cleanup = onCleanup(@() cd(originalDirectory));
cd(path);
path = string(pwd);
clear cleanup
end

function mustBeValidSupplement(supplement)
if ~isfield(supplement,"schema") || supplement.schema ~= "portable-variable-supplement-v1"
    error("WaveVortexModel:InvalidPortableVariableSupplement", ...
        "The portability supplement has an unsupported schema.");
end
variables = supplement.variables;
ordinals = double([variables.ordinal]);
names = string({variables.name});
if ~isequal(ordinals,0:numel(variables)-1) || numel(unique(names)) ~= numel(names)
    error("WaveVortexModel:InvalidPortableVariableSupplement", ...
        "Portable variable ordinals must be contiguous and names unique.");
end
end

function annotations = authoritativeAnnotations(definitions)
annotations = containers.Map(KeyType="char",ValueType="any");
coefficientNames = {'Ap','Am','A0'};
allPropertyAnnotations = WVTransform.propertyAnnotationsForTransform( ...
    coefficientNames{:},spectralDimensionNames={'j','kl'});
for iAnnotation = 1:numel(allPropertyAnnotations)
    annotation = allPropertyAnnotations(iAnnotation);
    if ismember(annotation.name,coefficientNames)
        annotations(annotation.name) = annotation;
    end
end

allNames = string({definitions.name});
fieldNames = cellstr(allNames(4:end));
operations = WVTransform.classDefinedOperationForKnownVariable( ...
    fieldNames{:},spatialDimensionNames={'x','y','z'}, ...
    spectralDimensionNames={'j','kl'});
for iOperation = 1:numel(operations)
    annotation = operations(iOperation).outputVariables;
    annotations(annotation.name) = annotation;
end
if annotations.Count ~= numel(definitions)
    error("WaveVortexModel:IncompletePortableVariableCatalog", ...
        "Expected %d authoritative annotations, found %d.", ...
        numel(definitions),annotations.Count);
end
end

function record = emptyVariableRecord()
record = struct( ...
    ordinal=0, ...
    name="", ...
    cppIdentifier="", ...
    dimensions=strings(1,0), ...
    units="", ...
    description="", ...
    isComplex=false, ...
    isVariableWithLinearTimeStep=false, ...
    isVariableWithNonlinearTimeStep=false, ...
    isDependentOnApAmA0=false, ...
    portableKind="", ...
    naturalRank="", ...
    samplingModes=strings(1,0), ...
    primitiveDependencyMask=uint64(0), ...
    movingPrimitiveChannel=int8(-1), ...
    netCDFAttributes=repmat(struct(name="",value=""),0,1));
end

function record = normalizedRecord(definition,annotation,dependencyValues)
record = emptyVariableRecord();
record.ordinal = double(definition.ordinal);
record.name = string(annotation.name);
record.cppIdentifier = string(definition.cppIdentifier);
record.dimensions = string(annotation.dimensions);
record.units = string(annotation.units);
record.description = string(annotation.description);
record.isComplex = logical(annotation.isComplex);
record.isVariableWithLinearTimeStep = logical(annotation.isVariableWithLinearTimeStep);
record.isVariableWithNonlinearTimeStep = logical(annotation.isVariableWithNonlinearTimeStep);
record.isDependentOnApAmA0 = logical(annotation.isDependentOnApAmA0);
record.portableKind = string(definition.portableKind);
record.naturalRank = string(definition.naturalRank);
record.samplingModes = string(definition.samplingModes(:)).';
record.movingPrimitiveChannel = int8(definition.movingPrimitiveChannel);

dependencyNames = string(definition.primitiveDependencies);
for iDependency = 1:numel(dependencyNames)
    name = char(dependencyNames(iDependency));
    if ~isfield(dependencyValues,name)
        error("WaveVortexModel:InvalidPortableVariableSupplement", ...
            "Unknown primitive dependency %s.",name);
    end
    record.primitiveDependencyMask = bitor(record.primitiveDependencyMask, ...
        uint64(dependencyValues.(name)));
end

attributes = annotation.attributes;
attributeNames = string(keys(attributes));
supplementAttributes = definition.netCDFAttributes;
if isstruct(supplementAttributes)
    attributeNames = [attributeNames,string(fieldnames(supplementAttributes)).'];
end
attributeNames = sort(unique(attributeNames));
record.netCDFAttributes = repmat(struct(name="",value=""),numel(attributeNames),1);
for iAttribute = 1:numel(attributeNames)
    name = attributeNames(iAttribute);
    if isKey(attributes,char(name))
        value = string(attributes(char(name)));
        if isstruct(supplementAttributes) && isfield(supplementAttributes,char(name)) && value ~= string(supplementAttributes.(char(name)))
            error("WaveVortexModel:InvalidPortableVariableSupplement","Conflicting NetCDF attribute %s for %s.",name,record.name);
        end
    else
        value = string(supplementAttributes.(char(name)));
    end
    record.netCDFAttributes(iAttribute) = struct(name=name,value=value);
end
end

function text = renderHeader(variables)
lines = [ ...
    "// Generated by tools/generatePortableVariableCatalog.m. Do not edit."; ...
    "#pragma once"; ...
    ""; ...
    "#include <array>"; ...
    "#include <cstddef>"; ...
    "#include <cstdint>"; ...
    "#include <string_view>"; ...
    ""; ...
    "namespace wavevortex::runtime {"; ...
    ""; ...
    "enum class WVPortableVariable : std::uint8_t {" ...
    ];
for iVariable = 1:numel(variables)
    definition = variables(iVariable);
    lines(end+1) = "  " + definition.cppIdentifier + " = " + ...
        definition.ordinal + ","; %#ok<AGROW>
end
lines = [lines; ...
    "  count = " + numel(variables) + ","; ...
    "  invalid = 255"; ...
    "};"; ...
    ""; ...
    "enum class WVPortableVariableKind : std::uint8_t { coefficient, field, diagnostic };"; ...
    "enum class WVPortableNaturalRank : std::uint8_t { coefficient, scalar, vertical, horizontal, volume };"; ...
    ""; ...
    "enum WVPortableSamplingMode : std::uint8_t {"; ...
    "  portableCoefficientSampling = 1U << 0,"; ...
    "  portableFullGridSampling = 1U << 1,"; ...
    "  portableFixedVerticalProfileSampling = 1U << 2,"; ...
    "  portablePositionSampling = 1U << 3"; ...
    "};"; ...
    ""; ...
    "struct WVPortableNetCDFAttribute {"; ...
    "  const char *name;"; ...
    "  const char *value;"; ...
    "};"; ...
    ""; ...
    "struct WVPortableVariableMetadata {"; ...
    "  WVPortableVariable identifier;"; ...
    "  std::uint8_t ordinal;"; ...
    "  const char *name;"; ...
    "  std::array<const char *, 3> dimensions;"; ...
    "  std::uint8_t dimensionCount;"; ...
    "  const char *units;"; ...
    "  const char *description;"; ...
    "  bool isComplex;"; ...
    "  bool isVariableWithLinearTimeStep;"; ...
    "  bool isVariableWithNonlinearTimeStep;"; ...
    "  bool isDependentOnApAmA0;"; ...
    "  WVPortableVariableKind kind;"; ...
    "  WVPortableNaturalRank naturalRank;"; ...
    "  std::uint8_t samplingMask;"; ...
    "  std::uint64_t primitiveDependencyMask;"; ...
    "  std::int8_t movingPrimitiveChannel;"; ...
    "  WVPortableNetCDFAttribute netCDFAttribute;"; ...
    "  std::uint8_t netCDFAttributeCount;"; ...
    "};"; ...
    ""; ...
    "inline constexpr std::array<WVPortableVariableMetadata, " + numel(variables) + ">"; ...
    "    WVPortableVariableCatalog{{" ...
    ];
for iVariable = 1:numel(variables)
    variable = variables(iVariable);
    dimensions = [variable.dimensions,strings(1,3-numel(variable.dimensions))];
    if isempty(variable.netCDFAttributes)
        attributeName = "";
        attributeValue = "";
        attributeCount = 0;
    else
        if numel(variable.netCDFAttributes) > 1
            error("WaveVortexModel:UnsupportedPortableVariableAttributeCount", ...
                "The generated C++ v1 catalog supports one static NetCDF attribute per variable.");
        end
        attributeName = variable.netCDFAttributes(1).name;
        attributeValue = variable.netCDFAttributes(1).value;
        attributeCount = 1;
    end
    line = "        {WVPortableVariable::" + variable.cppIdentifier + ...
        ", " + variable.ordinal + ", " + cppString(variable.name) + ...
        ", {{" + join(arrayfun(@cppString,dimensions),", ") + "}}, " + ...
        numel(variable.dimensions) + ", " + cppString(variable.units) + ...
        ", " + cppString(variable.description) + ", " + ...
        cppBoolean(variable.isComplex) + ", " + ...
        cppBoolean(variable.isVariableWithLinearTimeStep) + ", " + ...
        cppBoolean(variable.isVariableWithNonlinearTimeStep) + ", " + ...
        cppBoolean(variable.isDependentOnApAmA0) + ...
        ", WVPortableVariableKind::" + variable.portableKind + ...
        ", WVPortableNaturalRank::" + variable.naturalRank + ", " + ...
        samplingMask(variable.samplingModes) + ", " + ...
        string(variable.primitiveDependencyMask) + ", " + ...
        string(variable.movingPrimitiveChannel) + ", {" + ...
        cppString(attributeName) + ", " + cppString(attributeValue) + ...
        "}, " + attributeCount + "}";
    if iVariable ~= numel(variables)
        line = line + ",";
    end
    lines(end+1) = line; %#ok<AGROW>
end
lines = [lines; ...
    "    }};"; ...
    ""; ...
    "inline constexpr const WVPortableVariableMetadata *"; ...
    "portableVariableMetadata(WVPortableVariable identifier) noexcept {"; ...
    "  const auto ordinal = static_cast<std::size_t>(identifier);"; ...
    "  return ordinal < WVPortableVariableCatalog.size()"; ...
    "             ? &WVPortableVariableCatalog[ordinal]"; ...
    "             : nullptr;"; ...
    "}"; ...
    ""; ...
    "inline constexpr const WVPortableVariableMetadata *"; ...
    "findPortableVariable(std::string_view name) noexcept {"; ...
    "  for (const auto &variable : WVPortableVariableCatalog)"; ...
    "    if (name == variable.name)"; ...
    "      return &variable;"; ...
    "  return nullptr;"; ...
    "}"; ...
    ""; ...
    "inline constexpr const WVPortableVariableMetadata *"; ...
    "findExecutablePortableVariable(std::string_view name) noexcept {"; ...
    "  const auto *entry = findPortableVariable(name);"; ...
    "  return entry && entry->kind != WVPortableVariableKind::diagnostic ? entry : nullptr;"; ...
    "}"; ...
    ""; ...
    "inline constexpr std::size_t portableVariableCatalogBytes() noexcept {"; ...
    "  return sizeof(WVPortableVariableCatalog);"; ...
    "}"; ...
    ""; ...
    "} // namespace wavevortex::runtime"; ...
    "" ...
    ];
text = join(lines,newline);
end

function mask = samplingMask(modes)
mask = uint8(0);
for mode = modes
    switch mode
        case "coefficients"
            mask = bitor(mask,uint8(1));
        case "fullGrid"
            mask = bitor(mask,uint8(2));
        case "fixedVerticalProfiles"
            mask = bitor(mask,uint8(4));
        case "positions"
            mask = bitor(mask,uint8(8));
        otherwise
            error("WaveVortexModel:InvalidPortableVariableSupplement", ...
                "Unknown sampling mode %s.",mode);
    end
end
mask = string(mask);
end

function value = cppBoolean(value)
if value
    value = "true";
else
    value = "false";
end
end

function value = cppString(value)
value = string(value);
value = replace(value,"\","\\");
value = replace(value,string(char(34)),string([char(92),char(34)]));
value = replace(value,newline,"\\n");
value = string(char(34)) + value + string(char(34));
end

function writeText(path,text)
folder = fileparts(path);
if ~isfolder(folder)
    mkdir(folder);
end
fileId = fopen(path,"w");
if fileId < 0
    error("WaveVortexModel:PortableVariableCatalogWriteFailed", ...
        "Unable to open %s for writing.",path);
end
cleanup = onCleanup(@() fclose(fileId));
fprintf(fileId,"%s",text);
end

function catalog = addDiagnosticContracts(catalog,supplement,inventory)
% Portability facts augment, but never replace, the MATLAB annotations.
names = string({catalog.variables.name});
definitions = supplement.diagnosticContracts;
if ~isequal(string({definitions.name}),names) || numel(unique(string({catalog.variables.cppIdentifier}))) ~= numel(names)
    error("WaveVortexModel:InvalidPortableVariableSupplement","Every variable needs one ordered dependency contract and unique C++ identity.");
end
rows = struct(ordinal={},configuration={},authority={},operationClass={},operationExpression={}, ...
    component={},metadata={},dependencies={},trueProfileDependencies={},intermediateMask={}, ...
    runtimeStatus={},samplingRestriction={},configurationRestriction={},catalogStatus={},netCDF={});
for iEntry = 1:numel(inventory)
    entry = inventory(iEntry);
    index = find(names == string(entry.annotation.name),1);
    definition = supplement.variables(index);
    contract = definitions(index);
    metadata = normalizedRecord(definition,entry.annotation,supplement.primitiveDependencies);
    if any(metadata.dimensions == "kl")
        metadata.naturalRank = "coefficient";
    else
        ranks = ["scalar","vertical","horizontal","volume"];
        metadata.naturalRank = ranks(numel(metadata.dimensions)+1);
    end
    if metadata.naturalRank == "horizontal"
        metadata.samplingModes(metadata.samplingModes == "fixedVerticalProfiles") = [];
    end
    dependencies = reshape(string(contract.dependencies),1,[]);
    isQG = ismember(entry.family,["barotropic","stratified-qg"]);
    coefficients = "A0";
    phasedCoefficients = "A0t";
    if ~isQG
        coefficients = ["Ap","Am","A0"];
        phasedCoefficients = ["Apt","Amt","A0t"];
    end
    if ismember(entry.component,["geostrophic","mda"])
        coefficients = "A0";
        phasedCoefficients = "A0t";
    elseif ismember(entry.component,["wave","inertial"])
        coefficients = ["Ap","Am"];
        phasedCoefficients = ["Apt","Amt"];
    end
    dependencies = expand(dependencies,"$coefficients",coefficients);
    dependencies = expand(dependencies,"$phasedCoefficients",phasedCoefficients);
    verticalVelocity = strings(1,0);
    if ismember(entry.family,["constant-nonhydrostatic","boussinesq"]), verticalVelocity="w"; end
    dependencies = expand(dependencies,"$nonhydrostaticW",verticalVelocity);
    trueProfileDependencies = strings(1,0);
    if any(dependencies == "$trueProfile"), trueProfileDependencies="rho_nm"; end
    dependencies(dependencies == "$trueProfile") = [];
    intermediateMask = uint64(0);
    for name = reshape(string(contract.intermediates),1,[])
        intermediateIndex = find(string({supplement.intermediates.name}) == name);
        if numel(intermediateIndex) ~= 1
            error("WaveVortexModel:InvalidPortableVariableSupplement","Unknown intermediate %s.",name);
        end
        intermediateMask = bitor(intermediateMask,bitshift(uint64(1),supplement.intermediates(intermediateIndex).ordinal));
    end
    operationClass = "dependent-property-or-method";
    operationExpression = "";
    if ~isempty(entry.annotation.modelOp)
        operationClass = string(class(entry.annotation.modelOp));
        if operationClass == "WVOperation"
            operationExpression = string(func2str(entry.annotation.modelOp.f));
        end
    end
    if strlength(metadata.units)==0 || strlength(metadata.description)==0 || numel(metadata.dimensions)>3
        error("WaveVortexModel:InvalidPortableVariableMetadata","Missing or unsupported metadata for %s.",metadata.name);
    end
    role = "diagnostic";
    if metadata.portableKind == "coefficient", role="state-coefficient"; end
    complexLayout = "real";
    if metadata.isComplex, complexLayout="split-real-imaginary"; end
    netCDF = struct(role=role,dimensionNames=metadata.dimensions, ...
        coordinateRoles=metadata.dimensions,complexLayout=complexLayout,spatialLayout="MATLAB-column-major", ...
        spectralLayout="MATLAB-hermitian-j-kl-or-kl",timeDimension="observer-event", ...
        attributes=metadata.netCDFAttributes);
    rows(end+1) = struct(ordinal=metadata.ordinal,configuration=entry.configuration, ...
        authority=entry.authority,operationClass=operationClass,operationExpression=operationExpression, ...
        component=entry.component,metadata=metadata,dependencies=dependencies, ...
        trueProfileDependencies=trueProfileDependencies,intermediateMask=intermediateMask, ...
        runtimeStatus=string(contract.runtimeStatus),samplingRestriction=string(contract.samplingRestriction), ...
        configurationRestriction=string(contract.configurationRestriction),catalogStatus="supported",netCDF=netCDF); %#ok<AGROW>
end
catalog.configurations = unique(string({rows.configuration}),"stable");
catalog.intermediates = supplement.intermediates;
catalog.contracts = rows;
catalog.exclusions = supplement.exclusions;
catalog.policy = struct(unknownOperation="intentional-incompatibility",customOperation="intentional-incompatibility", ...
    forcingInstance="bind-template-and-verify-built-in-forcing-contract-before-evaluation", ...
    noMotionSolvers=["lsqnonlin","fminsearch"],cache="event-scoped-scratch-no-new-persistent-state-sized-cache");
end

function names = expand(names,token,replacement)
if any(names == token)
    names(names == token) = [];
    names = [names,replacement];
end
end

function text = renderVariableDocumentation(catalog)
lines = ["# Portable variable contracts";""; ...
    "Generated by `tools/generatePortableVariableCatalog.m` from MATLAB annotations and the portability supplement. Do not edit this table.";""; ...
    "Ordinals 0–22 and their canonical metadata retain the original output contract. Configuration rows carry the exact MATLAB dimensions and flags for each transform. A catalog contract does not enable numerical evaluation: new diagnostics wait for #305, forcing tendencies for #315. Runtime planners reject those entries before allocating field storage.";""; ...
    "Both antialias modes are inventoried for each family. `shouldUseTrueNoMotionProfile` selects the conditional `rho_nm` dependency. No-motion solver identity (`lsqnonlin` or `fminsearch`) must be supplied explicitly. Metadata generation never runs either solver. Intermediates have event-scoped lifetimes; annotation cache flags describe existing MATLAB behavior.";""; ...
    "NetCDF rows retain annotation attributes, MATLAB dimension order, split complex representation and observer-event time association. These are metadata contracts; they do not introduce an output schema for unevaluated diagnostics.";""; ...
    "Forcing exemplar names ending in `_portable_catalog_forcing` define templates: bind the actual MATLAB-sanitized instance name, qualified forcing identity and stage at construction. Reject duplicate resulting names. Custom operations, unqualified forcing instances and unknown configurations are incompatible.";""; ...
    "| Ordinal | MATLAB name | Units | Canonical dimensions | Runtime | Configurations | Dependencies |"; ...
    "| --- | --- | --- | --- | --- | --- | --- |"];
for variable = reshape(catalog.variables,1,[])
    rows = catalog.contracts([catalog.contracts.ordinal] == variable.ordinal);
    dependencies = strings(1,0);
    for row = reshape(rows,1,[])
        dependencies = [dependencies,row.dependencies,row.trueProfileDependencies + " (true profile)"]; %#ok<AGROW>
    end
    lines(end+1) = "| " + variable.ordinal + " | `" + variable.name + "` | " + variable.units + ...
        " | " + joinNonempty(variable.dimensions,",") + " | " + rows(1).runtimeStatus + " | " + ...
        join(unique(erase(string({rows.configuration}),["-aa0","-aa1"])),", ") + ...
        " | " + joinNonempty(unique(dependencies),", ") + " |"; %#ok<AGROW>
end
lines = [lines;"";"## Intentional incompatibilities";""; ...
    "These APIs lack a currently registered or callable variable annotation contract. Their mathematical methods remain available in MATLAB. Component energy is represented by the working `energy_<component>` factory.";""; ...
    "| MATLAB API | Reason |";"| --- | --- |"];
for row = reshape(catalog.exclusions,1,[])
    lines(end+1) = "| `" + string(row.name) + "` | " + string(row.reason) + " |"; %#ok<AGROW>
end
lines = [lines;"";"## Sampling and reusable intermediates";""; ...
    "Existing sampling modes are preserved. New fields support a full-grid contract only; new scalar reductions support scalar output, and phased coefficients retain spectral layout. Interpolation of new diagnostics requires separate numerical qualification in #305.";""; ...
    "| Intermediate | Lifetime | Purpose |";"| --- | --- | --- |"];
for row = reshape(catalog.intermediates,1,[])
    lines(end+1) = "| `" + string(row.name) + "` | " + string(row.lifetime) + " | " + string(row.description) + " |"; %#ok<AGROW>
end
text = join([lines;""],newline);
end

function value = joinNonempty(values,delimiter)
if isempty(values), value=""; else, value=join(reshape(values,1,[]),delimiter); end
end
