function result = generatePortableForwardIntegrationCatalog(options)
% Generate the forward-integration assembly slice and its matching guide.
arguments
    options.repositoryRoot (1,1) string = string(fileparts(fileparts(mfilename("fullpath"))))
    options.outputRoot (1,1) string = ""
end
if options.outputRoot=="", options.outputRoot=options.repositoryRoot; end
catalog = portableForwardIntegrationDefinition();
validatePortableForwardIntegrationCatalog(catalog,repositoryRoot=options.repositoryRoot);
catalogPath = fullfile(options.outputRoot,"PortableRuntime","contracts","portable-forward-integration-v1.json");
documentationPath = fullfile(options.outputRoot,"PortableRuntime","INTEGRATION.md");
writeText(catalogPath,string(jsonencode(catalog,PrettyPrint=true))+newline);
writeText(documentationPath,renderDocumentation(catalog));
result = struct(catalogPath=catalogPath,documentationPath=documentationPath,catalog=catalog);
end

function value = renderDocumentation(catalog)
lines = ["# Forward integration";""; ...
    "Generated by `generatePortableForwardIntegrationCatalog` from the versioned integration definition. Do not edit this file directly.";""; ...
    "The [versioned catalog](contracts/portable-forward-integration-v1.json) contains 30 supported configuration/profile rows. It is the integration slice for future #306 assembly; it does not declare complete model compatibility or decide #307 parity.";""; ...
    "## Supported configurations and profiles";""; ...
    "Each configuration supports explicit RK4, CFL-selected RK4, adaptive RK3(2), adaptive RK4(5) and adaptive RK7(8). Source witnesses identify concrete existing tests; the table does not claim 30 newly executed full trajectories.";""; ...
    "| Configuration | Transform | Representative lifecycle profile | Case |"; ...
    "| --- | --- | --- | --- |"];
for k = 1:numel(catalog.configurations)
    configuration = catalog.configurations(k); item = catalog.cases(k);
    lines(end+1) = "| "+configuration.id+" | `"+configuration.transform+"` | "+item.profile+" | `"+item.id+"` |"; %#ok<AGROW>
end
lines = [lines;"";"## Source witnesses";"";"| Witness | Test | Coverage |";"| --- | --- | --- |"];
for item = catalog.witnesses
    lines(end+1) = "| `"+item.id+"` | ["+item.symbol+"](../"+item.path+") | "+item.coverage+" |"; %#ok<AGROW>
end
lines = [lines;"";"## Evidence scope";"";catalog.evidencePolicy;""; ...
    "The six representative lifecycle cases cover composed forcing, dense and ordinary output, independent destinations, segmentation, MATLAB/C++ restart in both directions, and continuation after a controlled stop. Their separate execution receipt records the actual providers, controls, results and source provenance. A missing or failed receipt cannot establish executed qualification. Older long-trajectory reports describe their original RK23/RK78 workloads; they are not fresh RK45 measurements.";""; ...
    "The catalog pins maximum relative coefficient/field/tracer/output error at `2e-7`, maximum particle position error at `0.02 m`, and maximum held-amplitude error at `1e-18`. Evolution must exceed `1e-6` in coefficients, `1e-4 m` in particle positions and `1e-8` in tracer state. Each complete receipt must retain all six case results for its provider, the actual runner/probe digests, and current source hashes. Inherited production-compatible evidence remains separately identified and preserves its original artifact and explicit correction history.";""; ...
    "Forcing applicability and diagnostic availability remain in the [forcing slice](contracts/portable-forcing-compatibility-v1.json) and [variable catalog](contracts/portable-variable-catalog-v1.json). This slice does not duplicate those feature matrices.";""; ...
    "## Explicit exclusions";""];
for item = catalog.exclusions
    lines(end+1) = "- **"+item.id+"** ("+item.reason+"): "+item.detail; %#ok<AGROW>
end
value = join(lines,newline)+newline;
end

function writeText(path,value)
folder = fileparts(path);
if ~isfolder(folder), mkdir(folder); end
fid = fopen(path,"w");
if fid < 0, error("WaveVortexModel:ForwardIntegrationWriteFailed","Cannot write %s.",path); end
cleanup = onCleanup(@()fclose(fid));
fprintf(fid,"%s",value);
end
