function report = prepareWaveVortexModelReleaseCandidate(repositoryRoot,oceanKitRoot,outputRoot,options)
%PREPAREWAVEVORTEXMODELRELEASECANDIDATE Build an unpublished patch export.
arguments
    repositoryRoot (1,1) string {mustBeFolder}
    oceanKitRoot (1,1) string {mustBeFolder}
    outputRoot (1,1) string
    options.releaseDate (1,1) string = string(datetime("today",TimeZone="UTC",Format="yyyy-MM-dd"))
end

if ~isfolder(outputRoot)
    mkdir(outputRoot);
end
manifestPath = fullfile(repositoryRoot,"resources","mpackage.json");
manifestBefore = jsondecode(fileread(manifestPath));
require(string(manifestBefore.name) == "WaveVortexModel", ...
    "The export dry run requires a WaveVortexModel authoring manifest.");
currentVersion = string(manifestBefore.version);
candidateVersion = nextPatchVersion(currentVersion);
configureIsolatedMPMRepository(oceanKitRoot);
packageBefore = matlab.mpm.Package(repositoryRoot);
require(string(packageBefore.ReleaseCompatibility) == ">=R2025b", ...
    "The export dry run requires MATLAB R2025b as the package compatibility floor.");

oceanKitTools = fullfile(oceanKitRoot,"tools");
sourceTools = fullfile(repositoryRoot,"tools");
originalPath = path;
pathCleanup = onCleanup(@()path(originalPath));
addpath(oceanKitTools,"-begin");
releaseFunction = @ci_release;
dependency = oceankitrelease.installDocumentationPackage("ClassDocumentation@1.3.2", ...
    repositoryRoot=oceanKitRoot);
require(dependency.Version == "1.3.2", ...
    "ClassDocumentation 1.3.2 was not installed for the export dry run.");
addpath(sourceTools,"-begin");
configureCIEnvironment(repositoryRoot,oceanKitRoot);

oceankitrelease.runDocumentationCheck(repositoryRoot,"docs:check");
expectedBody = oceankitrelease.unreleasedBody(fullfile(repositoryRoot,"CHANGELOG.md"));
releaseBodyPath = fullfile(outputRoot,"release-body.md");
releaseFunction( ...
    rootDir=repositoryRoot, ...
    bumpType="patch", ...
    shouldBuildWebsiteDocumentation=true, ...
    shouldPackageForDistribution=true, ...
    shouldPromoteUnreleased=true, ...
    shouldRequireDocumentationBuilder=true, ...
    releaseDate=options.releaseDate, ...
    releaseBodyPath=releaseBodyPath, ...
    outputRoot=outputRoot);

changedPaths = oceankitrelease.changedAuthoringPaths(repositoryRoot,"pilot");
expectedPaths = ["CHANGELOG.md";"docs/version-history.md";"resources/mpackage.json"];
require(isequal(changedPaths,expectedPaths), ...
    "The export dry run changed files outside the permitted release-owned set.");
manifestAfter = jsondecode(fileread(manifestPath));
require(string(manifestAfter.version) == candidateVersion, ...
    "The export dry run did not create the expected " + candidateVersion + " candidate.");
actualBody = string(fileread(releaseBodyPath));
require(strtrim(actualBody) == strtrim(expectedBody), ...
    "The release-body file does not match the promoted Unreleased body.");

changelog = string(fileread(fullfile(repositoryRoot,"CHANGELOG.md")));
escapedVersion = regexptranslate("escape",candidateVersion);
unreleasedMatch = regexp(changelog,'(?s)^.*?## \[Unreleased\]\s*## \[' + escapedVersion + '\] - [^\r\n]+','once','match');
require(~isempty(unreleasedMatch), ...
    "The promoted changelog does not begin with a fresh empty Unreleased section.");
changelogBody = versionBody(fullfile(repositoryRoot,"CHANGELOG.md"),candidateVersion);
require(contains(changelog,"## [" + candidateVersion + "] - " + options.releaseDate) && changelogBody == expectedBody, ...
    "The promoted changelog does not contain the expected dated release body.");
versionHistory = string(fileread(fullfile(repositoryRoot,"docs","version-history.md")));
versionHistoryBody = versionBody(fullfile(repositoryRoot,"docs","version-history.md"),candidateVersion);
require(contains(versionHistory,"## [" + candidateVersion + "] - " + options.releaseDate) && versionHistoryBody == expectedBody, ...
    "The generated version history does not agree with the promoted changelog.");

exportPath = fullfile(outputRoot,"WaveVortexModel-" + candidateVersion);
require(isfolder(exportPath),"The expected WaveVortexModel-" + candidateVersion + " export was not created.");
exportManifest = jsondecode(fileread(fullfile(exportPath,"resources","mpackage.json")));
exportFolders = string({exportManifest.folders.path});
require(string(exportManifest.version) == candidateVersion && ~any(exportFolders == "UnitTests"), ...
    "The exported manifest does not describe the expected runtime package.");
exportPackage = matlab.mpm.Package(exportPath);
require(string(exportPackage.ReleaseCompatibility) == ">=R2025b", ...
    "The exported package does not retain the MATLAB R2025b compatibility floor.");
requiredRuntimeSources = [ ...
    "CompiledKernel/CMakeLists.txt"; ...
    "CompiledKernel/native-fftw-provider.env"; ...
    "CompiledKernel/include/WaveVortexKernel/WVFFTEngine.hpp"; ...
    "CompiledKernel/src/WVTransformConstantStratificationKernel.cpp"; ...
    "CompiledKernel/adapters/native-fftw/WVNativeFFTWEngine.cpp"; ...
    "PortableRuntime/CMakeLists.txt"; ...
    "PortableRuntime/buildWaveVortexRun.sh"; ...
    "PortableRuntime/include/WaveVortexRuntime/WVIntegrationState.hpp"; ...
    "PortableRuntime/include/WaveVortexRuntime/WVRungeKutta.hpp"; ...
    "PortableRuntime/include/WaveVortexRuntime/WVOutputOrchestration.hpp"; ...
    "PortableRuntime/src/WVIntegrationState.cpp"; ...
    "PortableRuntime/src/WVRungeKutta.cpp"; ...
    "PortableRuntime/src/WVOutputOrchestration.cpp"; ...
    "PortableRuntime/app/WaveVortexRun.cpp"];
for relativePath = requiredRuntimeSources'
    require(isfile(fullfile(exportPath,relativePath)), ...
        "The exported package is missing required portable-runtime source " + relativePath + ".");
end
[attributeStatus,attributes] = fileattrib(fullfile(exportPath,"PortableRuntime","buildWaveVortexRun.sh"));
require(attributeStatus && attributes.UserExecute, ...
    "The exported portable-runtime build script is not executable.");
exportedFiles = string({dir(fullfile(exportPath,"**","*")).name});
forbiddenNames = endsWith(exportedFiles,[".a" ".o" ".dylib" ".so" ".tar.gz"]) | startsWith(exportedFiles,"wave-vortex-run");
require(~any(forbiddenNames), ...
    "The exported package contains a compiled product or downloaded archive.");

report = struct( ...
    "sourceVersion",currentVersion, ...
    "version",candidateVersion, ...
    "releaseCompatibility",string(exportPackage.ReleaseCompatibility), ...
    "exportPath",exportPath, ...
    "releaseBodyPath",releaseBodyPath, ...
    "releaseBody",expectedBody, ...
    "authoringPaths",changedPaths, ...
    "documentationPackageRoot",dependency.Root);
fprintf("Prepared unpublished WaveVortexModel %s candidate at %s.\n",candidateVersion,exportPath);
clear pathCleanup
end

function version = nextPatchVersion(currentVersion)
tokens = regexp(currentVersion,'^(\d+)\.(\d+)\.(\d+)$','tokens','once');
require(~isempty(tokens),"The WaveVortexModel version must use major.minor.patch format.");
version = string(sprintf("%d.%d.%d",str2double(tokens{1}),str2double(tokens{2}),str2double(tokens{3})+1));
end

function body = versionBody(path,version)
source = fileread(path);
escapedVersion = regexptranslate("escape",version);
[~,headingEnd] = regexp(source,'(?m)^## \[' + escapedVersion + '\][^\r\n]*\r?\n','once','start','end');
if isempty(headingEnd)
    error("WaveVortexModel:ReleaseCandidateVerificationFailed", ...
        "Version %s was not found in %s.",version,path);
end
followingText = source(headingEnd+1:end);
nextHeading = regexp(followingText,'(?m)^## \[','once','start');
if isempty(nextHeading)
    rawBody = followingText;
else
    rawBody = followingText(1:nextHeading-1);
end
body = string(regexprep(rawBody,'^\s*|\s*$',''));
end

function require(condition,message)
if ~condition
    error("WaveVortexModel:ReleaseCandidateVerificationFailed","%s",message);
end
end
