function report = prepareWaveVortexModelReleaseCandidate(repositoryRoot,oceanKitRoot,outputRoot,options)
%PREPAREWAVEVORTEXMODELRELEASECANDIDATE Validate an unpublished or current export.
arguments
    repositoryRoot (1,1) string {mustBeFolder}
    oceanKitRoot (1,1) string {mustBeFolder}
    outputRoot (1,1) string
    options.releaseDate (1,1) string = string(datetime("today",TimeZone="UTC",Format="yyyy-MM-dd"))
end

if ~isfolder(outputRoot)
    mkdir(outputRoot);
end
manifestPath = fullfile(repositoryRoot,"resources","mpackage.json");
manifestBefore = jsondecode(fileread(manifestPath));
require(string(manifestBefore.name) == "WaveVortexModel", ...
    "The export dry run requires a WaveVortexModel authoring manifest.");
currentVersion = string(manifestBefore.version);
configureIsolatedMPMRepository(oceanKitRoot);
packageBefore = matlab.mpm.Package(repositoryRoot);
require(string(packageBefore.ReleaseCompatibility) == ">=R2025b", ...
    "The export dry run requires MATLAB R2025b as the package compatibility floor.");

oceanKitTools = fullfile(oceanKitRoot,"tools");
sourceTools = fullfile(repositoryRoot,"tools");
originalPath = path;
pathCleanup = onCleanup(@()path(originalPath));
addpath(oceanKitTools,"-begin");
releaseFunction = @ci_release;
dependency = oceankitrelease.installDocumentationPackage("ClassDocumentation@1.3.2", ...
    repositoryRoot=oceanKitRoot);
require(dependency.Version == "1.3.2", ...
    "ClassDocumentation 1.3.2 was not installed for the export dry run.");
addpath(sourceTools,"-begin");
configureCIEnvironment(repositoryRoot,oceanKitRoot);

oceankitrelease.runDocumentationCheck(repositoryRoot,"docs:check");
changelogPath = fullfile(repositoryRoot,"CHANGELOG.md");
try
    expectedBody = oceankitrelease.unreleasedBody(changelogPath);
    shouldPromoteUnreleased = true;
catch exception
    if exception.identifier ~= "OceanKitRelease:EmptyUnreleasedSection"
        rethrow(exception);
    end
    expectedBody = "";
    shouldPromoteUnreleased = false;
end
if shouldPromoteUnreleased
    candidateVersion = nextPatchVersion(currentVersion);
    bumpType = "patch";
    releaseBodyPath = fullfile(outputRoot,"release-body.md");
else
    candidateVersion = currentVersion;
    bumpType = "none";
    releaseBodyPath = "";
end
releaseFunction( ...
    rootDir=repositoryRoot, ...
    bumpType=bumpType, ...
    shouldBuildWebsiteDocumentation=true, ...
    shouldPackageForDistribution=true, ...
    shouldPromoteUnreleased=shouldPromoteUnreleased, ...
    shouldRequireDocumentationBuilder=true, ...
    releaseDate=options.releaseDate, ...
    releaseBodyPath=releaseBodyPath, ...
    outputRoot=outputRoot);

changedPaths = oceankitrelease.changedAuthoringPaths(repositoryRoot,"pilot");
if shouldPromoteUnreleased
    expectedPaths = ["CHANGELOG.md";"docs/version-history.md";"resources/mpackage.json"];
else
    expectedPaths = strings(0,1);
end
require(isequal(changedPaths,expectedPaths), ...
    "The export dry run changed files outside the permitted release-owned set.");
manifestAfter = jsondecode(fileread(manifestPath));
require(string(manifestAfter.version) == candidateVersion, ...
    "The export dry run did not create the expected " + candidateVersion + " candidate.");
if shouldPromoteUnreleased
    actualBody = string(fileread(releaseBodyPath));
    require(strtrim(actualBody) == strtrim(expectedBody), ...
        "The release-body file does not match the promoted Unreleased body.");

    changelog = string(fileread(changelogPath));
    escapedVersion = regexptranslate("escape",candidateVersion);
    unreleasedMatch = regexp(changelog,'(?s)^.*?## \[Unreleased\]\s*## \[' + escapedVersion + '\] - [^\r\n]+','once','match');
    require(~isempty(unreleasedMatch), ...
        "The promoted changelog does not begin with a fresh empty Unreleased section.");
    changelogBody = versionBody(changelogPath,candidateVersion);
    require(contains(changelog,"## [" + candidateVersion + "] - " + options.releaseDate) && changelogBody == expectedBody, ...
        "The promoted changelog does not contain the expected dated release body.");
    versionHistory = string(fileread(fullfile(repositoryRoot,"docs","version-history.md")));
    versionHistoryBody = versionBody(fullfile(repositoryRoot,"docs","version-history.md"),candidateVersion);
    require(contains(versionHistory,"## [" + candidateVersion + "] - " + options.releaseDate) && versionHistoryBody == expectedBody, ...
        "The generated version history does not agree with the promoted changelog.");
end

exportPath = fullfile(outputRoot,"WaveVortexModel-" + candidateVersion);
require(isfolder(exportPath),"The expected WaveVortexModel-" + candidateVersion + " export was not created.");
exportManifest = jsondecode(fileread(fullfile(exportPath,"resources","mpackage.json")));
exportFolders = string({exportManifest.folders.path});
require(string(exportManifest.version) == candidateVersion && ~any(exportFolders == "UnitTests"), ...
    "The exported manifest does not describe the expected runtime package.");
exportPackage = matlab.mpm.Package(exportPath);
require(string(exportPackage.ReleaseCompatibility) == ">=R2025b", ...
    "The exported package does not retain the MATLAB R2025b compatibility floor.");
requiredRuntimeSources = [ ...
    "CompiledKernel/CMakeLists.txt"; ...
    "CompiledKernel/native-fftw-provider.env"; ...
    "CompiledKernel/include/WaveVortexKernel/WVFFTEngine.hpp"; ...
    "CompiledKernel/include/WaveVortexKernel/WVTransformBarotropicQGKernel.hpp"; ...
    "CompiledKernel/src/WVTransformBarotropicQGKernel.cpp"; ...
    "CompiledKernel/src/WVTransformConstantStratificationKernel.cpp"; ...
    "CompiledKernel/adapters/native-fftw/WVNativeFFTWEngine.cpp"; ...
    "PortableRuntime/CMakeLists.txt"; ...
    "PortableRuntime/README.md"; ...
    "PortableRuntime/buildWaveVortexRun.sh"; ...
    "PortableRuntime/source-selection.json"; ...
    "PortableRuntime/include/WaveVortexRuntime/WVCheckpointReader.hpp"; ...
    "PortableRuntime/include/WaveVortexRuntime/WVExtensionCatalog.hpp"; ...
    "PortableRuntime/include/WaveVortexRuntime/WVFieldEvaluationService.hpp"; ...
    "PortableRuntime/include/WaveVortexRuntime/WVForcing.hpp"; ...
    "PortableRuntime/include/WaveVortexRuntime/WVForcingContracts.hpp"; ...
    "PortableRuntime/include/WaveVortexRuntime/WVIntegrationState.hpp"; ...
    "PortableRuntime/include/WaveVortexRuntime/WVBarotropicQGForcingEngine.hpp"; ...
    "PortableRuntime/include/WaveVortexRuntime/WVBarotropicQGIntegrationSystem.hpp"; ...
    "PortableRuntime/include/WaveVortexRuntime/WVModel.hpp"; ...
    "PortableRuntime/include/WaveVortexRuntime/WVModelOutputConfiguration.hpp"; ...
    "PortableRuntime/include/WaveVortexRuntime/WVModelOutputNetCDF.hpp"; ...
    "PortableRuntime/include/WaveVortexRuntime/WVObservation.hpp"; ...
    "PortableRuntime/include/WaveVortexRuntime/WVObserverContracts.hpp"; ...
    "PortableRuntime/include/WaveVortexRuntime/WVObserverOutputEvaluationService.hpp"; ...
    "PortableRuntime/include/WaveVortexRuntime/WVObserverOutputProvider.hpp"; ...
    "PortableRuntime/include/WaveVortexRuntime/WVObservingSystem.hpp"; ...
    "PortableRuntime/include/WaveVortexRuntime/WVRungeKutta.hpp"; ...
    "PortableRuntime/include/WaveVortexRuntime/WVOutputOrchestration.hpp"; ...
    "PortableRuntime/include/WaveVortexRuntime/WVOutputSchedule.hpp"; ...
    "PortableRuntime/include/WaveVortexRuntime/WVPortableImplementationContract.hpp"; ...
    "PortableRuntime/include/WaveVortexRuntime/WVPortableTypedRecord.hpp"; ...
    "PortableRuntime/include/WaveVortexRuntime/WVRunner.hpp"; ...
    "PortableRuntime/src/WVCheckpointTransformAdapters.cpp"; ...
    "PortableRuntime/src/WVBarotropicQGFieldEvaluationAdapter.cpp"; ...
    "PortableRuntime/src/WVBarotropicQGFieldEvaluationAdapter.hpp"; ...
    "PortableRuntime/src/WVExtensionCatalog.cpp"; ...
    "PortableRuntime/src/WVFieldEvaluationService.cpp"; ...
    "PortableRuntime/src/WVIntegrationState.cpp"; ...
    "PortableRuntime/src/WVBarotropicQGForcingEngine.cpp"; ...
    "PortableRuntime/src/WVBarotropicQGIntegrationSystem.cpp"; ...
    "PortableRuntime/src/WVLegacyObserverCompatibility.hpp"; ...
    "PortableRuntime/src/WVModelInternalAccess.hpp"; ...
    "PortableRuntime/src/WVModelOutputConfiguration.cpp"; ...
    "PortableRuntime/src/WVModelOutputNetCDFReader.cpp"; ...
    "PortableRuntime/src/WVModelOutputTransformAdapters.cpp"; ...
    "PortableRuntime/src/WVModelOutputTransformAdapters.hpp"; ...
    "PortableRuntime/src/WVModelOutputNetCDFWriter.cpp"; ...
    "PortableRuntime/src/WVModelTransformAdapters.cpp"; ...
    "PortableRuntime/src/WVModelTransformAdapters.hpp"; ...
    "PortableRuntime/src/WVObservation.cpp"; ...
    "PortableRuntime/src/WVObserverContracts.cpp"; ...
    "PortableRuntime/src/WVObserverOutputEvaluationService.cpp"; ...
    "PortableRuntime/src/WVObserverSampleSource.cpp"; ...
    "PortableRuntime/src/WVRungeKutta.cpp"; ...
    "PortableRuntime/src/WVOutputOrchestration.cpp"; ...
    "PortableRuntime/src/WVOutputTransformAdapters.cpp"; ...
    "PortableRuntime/src/WVOutputTransformAdapters.hpp"; ...
    "PortableRuntime/src/WVOutputSchedule.cpp"; ...
    "PortableRuntime/src/WVModel.cpp"; ...
    "PortableRuntime/app/WaveVortexRun.cpp"; ...
    "PortableRuntime/app/WaveVortexRunMain.cpp"; ...
    "PortableRuntime/app/WVRunRequest.cpp"; ...
    "PortableRuntime/app/WVRunRequest.hpp"; ...
    "PortableRuntime/contracts/wave-vortex-run-request-v1.schema.json"; ...
    "PortableRuntime/examples/portable-run-request-v1.json"; ...
    "PortableRuntime/third_party/nlohmann/json.hpp"; ...
    "PortableRuntime/third_party/nlohmann/LICENSE.MIT"];
for relativePath = requiredRuntimeSources'
    require(isfile(fullfile(exportPath,relativePath)), ...
        "The exported package is missing required portable-runtime source " + relativePath + ".");
end
[attributeStatus,attributes] = fileattrib(fullfile(exportPath,"PortableRuntime","buildWaveVortexRun.sh"));
require(attributeStatus && attributes.UserExecute, ...
    "The exported portable-runtime build script is not executable.");
exportedFiles = string({dir(fullfile(exportPath,"**","*")).name});
compiledRunnerNames = exportedFiles == "wave-vortex-run" | exportedFiles == "wave-vortex-run.exe";
forbiddenNames = endsWith(exportedFiles,[".a" ".o" ".dylib" ".so" ".tar.gz"]) | compiledRunnerNames;
require(~any(forbiddenNames), ...
    "The exported package contains a compiled product or downloaded archive.");

report = struct( ...
    "sourceVersion",currentVersion, ...
    "version",candidateVersion, ...
    "releaseCompatibility",string(exportPackage.ReleaseCompatibility), ...
    "exportPath",exportPath, ...
    "releaseBodyPath",releaseBodyPath, ...
    "releaseBody",expectedBody, ...
    "authoringPaths",changedPaths, ...
    "documentationPackageRoot",dependency.Root);
fprintf("Prepared WaveVortexModel %s export at %s.\n",candidateVersion,exportPath);
clear pathCleanup
end

function version = nextPatchVersion(currentVersion)
tokens = regexp(currentVersion,'^(\d+)\.(\d+)\.(\d+)$','tokens','once');
require(~isempty(tokens),"The WaveVortexModel version must use major.minor.patch format.");
version = string(sprintf("%d.%d.%d",str2double(tokens{1}),str2double(tokens{2}),str2double(tokens{3})+1));
end

function body = versionBody(path,version)
source = fileread(path);
escapedVersion = regexptranslate("escape",version);
[~,headingEnd] = regexp(source,'(?m)^## \[' + escapedVersion + '\][^\r\n]*\r?\n','once','start','end');
if isempty(headingEnd)
    error("WaveVortexModel:ReleaseCandidateVerificationFailed", ...
        "Version %s was not found in %s.",version,path);
end
followingText = source(headingEnd+1:end);
nextHeading = regexp(followingText,'(?m)^## \[','once','start');
if isempty(nextHeading)
    rawBody = followingText;
else
    rawBody = followingText(1:nextHeading-1);
end
body = string(regexprep(rawBody,'^\s*|\s*$',''));
end

function require(condition,message)
if ~condition
    error("WaveVortexModel:ReleaseCandidateVerificationFailed","%s",message);
end
end
