function configuration = wvCompiledConstantConfiguration(wvt)
% Build the immutable MATLAB ABI for a constant-stratification transform.

arguments
    wvt (1,1) WVTransformConstantStratification
end

configuration = struct( ...
    "schemaVersion",'wv-matlab-stratified-modal-source-v1', ...
    "transformClass",char(class(wvt)), ...
    "modelVersion",char(wvt.version), ...
    "Nx",wvt.Nx,"Ny",wvt.Ny,"Nz",wvt.Nz,"Nj",wvt.Nj,"Nkl",wvt.Nkl, ...
    "Lx",wvt.Lx,"Ly",wvt.Ly,"Lz",wvt.Lz,"g",wvt.g,"rho0",wvt.rho0,"N0",wvt.N0, ...
    "latitude",wvt.latitude,"rotationRate",wvt.rotationRate,"planetaryRadius",wvt.planetaryRadius, ...
    "shouldAntialias",wvt.shouldAntialias,"isHydrostatic",wvt.isHydrostatic);
end
