function configuration = wvCompiledStratifiedModalConfiguration(wvt)
% Build the immutable MATLAB ABI for a stratified modal source.

arguments
    wvt (1,1) WVTransform
end

if ~ismember(string(class(wvt)),["WVTransformHydrostatic" "WVTransformBoussinesq" "WVTransformStratifiedQG"])
    error("WaveVortexModel:CompiledTransformUnsupportedFamily","Compiled MATLAB support currently covers Hydrostatic, Boussinesq and Stratified QG transforms.")
end

configuration = struct( ...
    "schemaVersion",'wv-matlab-stratified-modal-source-v1', ...
    "transformClass",char(class(wvt)), ...
    "modelVersion",char(wvt.version), ...
    "Nx",wvt.Nx,"Ny",wvt.Ny,"Nz",wvt.Nz,"Nj",wvt.Nj,"Nkl",wvt.Nkl, ...
    "Lx",wvt.Lx,"Ly",wvt.Ly,"Lz",wvt.Lz,"g",wvt.g,"rho0",wvt.rho0, ...
    "latitude",wvt.latitude,"rotationRate",wvt.rotationRate,"planetaryRadius",wvt.planetaryRadius, ...
    "shouldAntialias",wvt.shouldAntialias, ...
    "x",wvt.x,"y",wvt.y,"z",wvt.z,"j",wvt.j,"k",wvt.k,"l",wvt.l, ...
    "kMode",wvt.kMode_wv,"lMode",wvt.lMode_wv, ...
    "N2",wvt.N2,"rho_nm0",wvt.rho_nm0,"dLnN2",wvt.dLnN2,"z_int",wvt.z_int, ...
    "P0",wvt.P0,"Q0",wvt.Q0,"h_0",wvt.h_0, ...
    "PF0inv",wvt.PF0inv,"QG0inv",wvt.QG0inv,"PF0",wvt.PF0,"QG0",wvt.QG0);
if isa(wvt,"WVTransformBoussinesq")
    configuration.K2unique = wvt.K2unique;
    configuration.iK2unique = wvt.iK2unique;
    configuration.h_pm = wvt.h_pm;
    configuration.Ppm = wvt.Ppm;
    configuration.Qpm = wvt.Qpm;
    configuration.PFpmInv = wvt.PFpmInv;
    configuration.QGpmInv = wvt.QGpmInv;
    configuration.PFpm = wvt.PFpm;
    configuration.QGpm = wvt.QGpm;
    configuration.QGwg = wvt.QGwg;
end
end
